### ISSUE TITLE
Conversation on the Missions

### ISSUE THREAD

**Issue by TheGiraffe3** [ProNooberEX/endless-sky#1]
Start the issue

**Comment by ProNooberEX** [comment]
I fine with both

**Comment by ProNooberEX** [comment]
Added you

**Comment by ProNooberEX** [comment]
I have added an additional choice to beginning spaceport event with the knife

**Comment by ProNooberEX** [comment]
Btw I find it is getting messy seeing all of the choices and their sub branches, is there a way for me to view these branches on a more organized level?

**Comment by ProNooberEX** [comment]
I have VSC on my mac, should I download the code file onto it and edit it there?

**Comment by ProNooberEX** [comment]
Ok I'll try

**Comment by ProNooberEX** [comment]
I can only see the "New Pull Request" Button

**Comment by ProNooberEX** [comment]
<img width="938" alt="截屏2024-06-12 18 29 24" src="https://github.com/ProNooberEX/endless-sky/assets/110284440/8d42c1d9-e25a-441b-9be6-90ab025a12ab">

**Comment by ProNooberEX** [comment]
Like this?

**Comment by ProNooberEX** [comment]
<img width="1260" alt="截屏2024-06-12 18 42 39" src="https://github.com/ProNooberEX/endless-sky/assets/110284440/7acd1270-8871-45c8-9da1-1dacfd0e110c">

**Comment by ProNooberEX** [comment]
<img width="921" alt="截屏2024-06-12 18 53 15" src="https://github.com/ProNooberEX/endless-sky/assets/110284440/2170c3c1-fdda-4832-a6b2-3ffe2fa9d519">
Like this then create pull request?

**Comment by ProNooberEX** [comment]
Thanks! Although I wonder at what the pull request are for.

**Comment by ProNooberEX** [comment]
Btw if you wish to replace the pirates building a wormhole idead, have you got any suggestions to legitimize the Southern pirates ability to raid the northern ones?

**Comment by ProNooberEX** [comment]
> Could they get Jump Drives?

They could but that wont make the quargs mad enough to launch an operation...

**Comment by ProNooberEX** [comment]
> I was thinking if they had them they could go through the Ember Waste, Korath space, then to Misam and go through the uninhabited systems between there and Arneb.

From the perspective of the pirates that would mean all of the raiding ships equppied with jump drives and enough defense and power to overcome Korath ships, if that is the case then I think the pirates would have taken over the entire galaxy along time ago.

**Comment by ProNooberEX** [comment]
> If not, I don’t know. We could add a string of systems up the west side of space, but that doesn’t really work well…

Maybe cloaking devices and ramscoops helping the pirate ships sail across the entire Republic space?

**Comment by ProNooberEX** [comment]
> But the chances of them having JD _are_ slim…

Or we could only add one unstable wormhole near the men systems and another in the northern pirate space, this case the pirates only need quantum keystones, which are easy to collect and feasible considering the pirates' powers

**Comment by ProNooberEX** [comment]
> > > But the chances of them having JD _are_ slim…
> > 
> > 
> > Or we could only add one unstable wormhole near the men systems and another in the northern pirate space, this case the pirates only need quantum keystones, which are easy to collect and feasible considering the pirates' powers
> 
> That would work. Maybe Fumalsamakah? And then Hatysa.

Yeah, or new systems could also do the trick

**Comment by ProNooberEX** [comment]
> > > > But the chances of them having JD _are_ slim…
> > > 
> > > 
> > > Or we could only add one unstable wormhole near the men systems and another in the northern pirate space, this case the pirates only need quantum keystones, which are easy to collect and feasible considering the pirates' powers
> > 
> > 
> > That would work. Maybe Fumalsamakah? And then Hatysa.
> 
> Yeah, or new systems could also do the trick

But again the problem is that the quargs wouldn't be mad in this case as the unstable wormholes already pre-exists.

**Comment by ProNooberEX** [comment]
> Well, the Quarg don’t like people attacking merchants—I tried once in Enif and was immediately destroyed. Then you could have it as some pirates hanged up and managed to take down and loot a Wardragon. That would get them in big trouble.

Do quarg ships enter the northern spaces that often?

**Comment by ProNooberEX** [comment]
> Good point. But they could have robbed the Quarg in the south and then gone north. Also, Hai space has Quarg who the northern pirates could attack-maybe.

Indeed, we could say that as the quargs and the northern pirates had rarely ever contacted, once they met the pirates would think its just a strange exotic looking vessel with powerfull weapons they crave and board it, causing the hostility of the quarg(similiar to what I did in the game on a previous file).

**Comment by ProNooberEX** [comment]
> > Good point. But they could have robbed the Quarg in the south and then gone north. Also, Hai space has Quarg who the northern pirates could attack-maybe.
> 
> Indeed, we could say that as the quargs and the northern pirates had rarely ever contacted, once they met the pirates would think its just a strange exotic looking vessel with powerfull weapons they crave and board it, causing the hostility of the quarg(similiar to what I did in the game on a previous file).

We can even add a stage where the southern pirates helped the local nothern pirates to hunt down the pirate lord responsible for the raid.

**Comment by ProNooberEX** [comment]
> Sounds good!

For this we would probably need to spawn a ship, a bactarian witth a few quarg skylances or other quarg technology for the matter.

**Comment by ProNooberEX** [comment]
> > Sounds good!
> 
> For this we would probably need to spawn a ship, a bactarian witth a few quarg skylances or other quarg technology for the matter.

The problem is I don't know how...

**Comment by ProNooberEX** [comment]
Then we would probably change the wormhole distraction to the quarg ship hunting distraction by sending a small fleet near Alycone's systems where the quarg sometimes appear when they are traveling from the syndicate space to the kor efreti space, fooling the quarg to think another hunt is going on.

**Comment by ProNooberEX** [comment]
> I’ve got the new Bactrian added.
> 
> > Then we would probably change the wormhole distraction to the quarg ship hunting distraction by sending a small fleet near Alycone's systems where the quarg sometimes appear when they are traveling from the syndicate space to the kor efreti space, fooling the quarg to think another hunt is going on.
> 
> Not sure what you mean there, can you clarify?

I mean in the original issue I released I plan to let the pirates create a wormhole that distracts the quarg as the quargs would send fleets to investigate the new rupture in time and space. But here as wormholes are not avaliable for construction I would shift it to let the pirates send out a small decoy fleet that captures the attention of the quarg by attacking quarg ships jumping into systems near Alycone from the Kor Efreti space where they have worlds and ringworlds, luring the majority of the quarg fleet from their planet to hunt this fleet, paving the way for the rest of the pirate fleet to storm the three quarg worlds near Tazard.

**Comment by ProNooberEX** [comment]
> Good to know.

My reasoning is that after the quarg lost their technology to ill intended pirates, they would want to desperately prevent further instances of quarg technology leaking into the pirates hands(who knows what raiders would do with it), therefore they would send their major forces to stop the fleet pretending to repeating the capture of technology, leaving weak defenses at their home worlds in human space.

**Comment by ProNooberEX** [comment]
> Yes, makes perfect sense.

Do you have any suggestions to the plot? there are just my personnal ideas so as a collaborator I want to hear your ideas as well.

**Comment by ProNooberEX** [comment]
Thank you! I am honored to hear this remark

**Comment by ProNooberEX** [comment]
Already did

**Comment by ProNooberEX** [comment]
> @ProNooberEX your most recent commits ([9654e88](https://github.com/ProNooberEX/endless-sky/commit/9654e888dceaf11867712999dd59670e0e209740), [44c421a](https://github.com/ProNooberEX/endless-sky/commit/44c421affbe2234ee83ceb7de8101353c0516adb), and [6553735](https://github.com/ProNooberEX/endless-sky/commit/655373576b6bce78e077ae51aa7679bb540a53d8)) were already in there. Why did you put them in again?
> 
> **Quarg**
> 
> [Ships](https://github.com/ProNooberEX/endless-sky/blob/655373576b6bce78e077ae51aa7679bb540a53d8/data/quarg/quarg%20ships.txt#L14) [Fleets](https://github.com/ProNooberEX/endless-sky/blob/655373576b6bce78e077ae51aa7679bb540a53d8/data/quarg/quarg.txt#L101)
> 
> **Pirates**
> 
> [Fleets](https://github.com/ProNooberEX/endless-sky/blob/655373576b6bce78e077ae51aa7679bb540a53d8/data/human/fleets.txt#L3559)

These files are not in the piratemission branch so that I decided to update the code there.

**Comment by ProNooberEX** [comment]
How do you set a mission completion requirement that forced the player to jump to both the northern pirate system and scan ships there in order to complete the mission?

**Comment by ProNooberEX** [comment]
May I ask the method to enable the mission to cotinue until all of the npc's fleet I added in pirate 0 beginning are scanned?(Similiar to the free world campaign where the player scans multiple ships of the Navy).?

**Comment by ProNooberEX** [comment]
> How do you mean? Looking at it, it should do that already.



> How do you mean? Looking at it, it should do that already.

So I don't need to set up a sort of counter mechanism to count the amount of ships scanned in the npc fleet until it reached the maximum number of ships in that fleet by myself?

**Comment by ProNooberEX** [comment]
> No. If you say `Large Northern Pirates` you can’t complete the mission until each ship spawned by that fleet has been scanned.
> 
> Also, can you make the default branch `master` for a minute? I’m trying to clean up commit history slightly but it doesn’t let me.

Got it, you can clean it up now

**Comment by ProNooberEX** [comment]
> Actually, looking at it it may be hard to do that, and we’ll just make a mess of it again, so I’ll clean it up once it’s merge-ready. You can set the default branch back to `piratemission`.

Did it as well

**Comment by ProNooberEX** [comment]
> Also, can you delete the `Dd` branch? I made it as part of cleaning up but for some reason can’t delete it now.

Did it too.

**Comment by ProNooberEX** [comment]
> Okay, that makes sense.

Btw why does Github has this protection thing?

**Comment by ProNooberEX** [comment]
> > Btw why does Github has this protection thing
> 
> You probably set it up somehow.
> 
> > Also I want to ask if we were to debug this how do we do it? Do we download and play out the plot of this edited version of the game or something out?
> 
> We copy the contents of the files we changed and put them in our data files. I only know the path in Mac, but you right-click (two fingers if you’re on the built-in touchpad) and then `Show Package Contents`. Then you go through the Contents folder into Resources/data/human, and put the pirate file in there. If this doesn’t make sense, say so, I may be able to clarify it more.

Ok now I see. and now may you help me inform on some of the bugs I have been recieveing from Github? I don't know what they are reporting.

**Comment by ProNooberEX** [comment]
> > Btw why does Github has this protection thing
> 
> You probably set it up somehow.
> 
> > Also I want to ask if we were to debug this how do we do it? Do we download and play out the plot of this edited version of the game or something out?
> 
> We copy the contents of the files we changed and put them in our data files. I only know the path in Mac, but you right-click (two fingers if you’re on the built-in touchpad) and then `Show Package Contents`. Then you go through the Contents folder into Resources/data/human, and put the pirate file in there. If this doesn’t make sense, say so, I may be able to clarify it more.

Also Didn't this pose the risk of messing up your file you are currently playing?

**Comment by ProNooberEX** [comment]
> > > > Btw why does Github has this protection thing
> > > 
> > > 
> > > You probably set it up somehow.
> > > > Also I want to ask if we were to debug this how do we do it? Do we download and play out the plot of this edited version of the game or something out?
> > > 
> > > 
> > > We copy the contents of the files we changed and put them in our data files. I only know the path in Mac, but you right-click (two fingers if you’re on the built-in touchpad) and then `Show Package Contents`. Then you go through the Contents folder into Resources/data/human, and put the pirate file in there. If this doesn’t make sense, say so, I may be able to clarify it more.
> > 
> > 
> > Ok now I see. and now may you help me inform on some of the bugs I have been recieveing from Github? I don't know what they are reporting.
> 
> What bugs?
> 
> Actually, I think that’s because I set up the Actions. They can probably be turned off.
<img width="738" alt="截屏2024-06-14 00 59 52" src="https://github.com/ProNooberEX/endless-sky/assets/110284440/b91963d3-690b-4ac7-a507-a56667c2af3a">
These stuff came ringing once and a while and I don't know how to fix them.

**Comment by ProNooberEX** [comment]
Btw I finished the beginning Mission for the pirate 0 beginning file, if you want you can check it out.

**Comment by ProNooberEX** [comment]
> Apparently I can’t turn them off because I’m not the repository owner. Do you want to try it? If not, we can leave it on and just delete the notifications. They don’t really do anything good for us right now.

Are these bugs genuine due to the code we've written being wrong?

**Comment by ProNooberEX** [comment]
> Well, GitHub doesn’t know what we’re doing. Those are checks the people in the main game wrote, but I think they may have dependencies not in this repository-aka we don’t have the information those tests need to pass, but it should work anyway. That’s guessing, but we can probably ignore them for now.

Would Zitchas and the other guys chase us down and be mad?

**Comment by ProNooberEX** [comment]
> Well, GitHub doesn’t know what we’re doing. Those are checks the people in the main game wrote, but I think they may have dependencies not in this repository-aka we don’t have the information those tests need to pass, but it should work anyway. That’s guessing, but we can probably ignore them for now.

Btw so the people in the main endless sky repository could see what we are doing?

**Comment by ProNooberEX** [comment]
> They can see what we’re doing if they manually go here, but the actions I don’t think they can see.

Ok thats good, I am just fearing they would get mad as us?(They probably would have wanted Zitchas' consent on updating the files)

**Comment by ProNooberEX** [comment]
> They want Zitchas’ permission for the Remnant stuff. But we’re not modifying that. And they can’t get mad at us, it’s a free project. They can not put it in, but they can’t get angry.

Ok that is good news, and btw why do you say it doesn't matter until we PR it?

**Comment by ProNooberEX** [comment]
> Because it’s not ready. Right now we don’t want it in the base game, and it’s okay if it fails some checks. Once it’s ready, it needs to pass the checks.

Wait...we are ACTUALLY adding this to the game?

**Comment by ProNooberEX** [comment]
Man this is a lifetime's opportunity...I never thought I would be actually leaving an imprint on the game I have been playing for 3 years.

**Comment by ProNooberEX** [comment]
> Well, they may not accept it. But I’ve been playing this for 5 months and have already contributed.

What did you add may I ask?

**Comment by ProNooberEX** [comment]
You think that, if our contribution is accepted...maybe Zitchas would give us Person Ships and ingrain our mark on the game for others to see?

**Comment by ProNooberEX** [comment]
Anyways this would be something for potentially thousands of players to see...which is truly a remarkable experience.

**Comment by ProNooberEX** [comment]
> > > > Btw why does Github has this protection thing
> > > 
> > > 
> > > You probably set it up somehow.
> > > > Also I want to ask if we were to debug this how do we do it? Do we download and play out the plot of this edited version of the game or something out?
> > > 
> > > 
> > > We copy the contents of the files we changed and put them in our data files. I only know the path in Mac, but you right-click (two fingers if you’re on the built-in touchpad) and then `Show Package Contents`. Then you go through the Contents folder into Resources/data/human, and put the pirate file in there. If this doesn’t make sense, say so, I may be able to clarify it more.
> > 
> > 
> > Also Didn't this pose the risk of messing up your file you are currently playing?
> 
> It does, so you’ll probably want to start a new game with the World Forge plugin. It’s a way to test content without messing up saves. Basically you start on a planet called Forge which has all outfits and ships available for sale.

Btw here you said a World Forge Plugin, where and how  could we add plugin to our game?(My game is on steam btw)

**Comment by ProNooberEX** [comment]
> > Btw I finished the beginning Mission for the pirate 0 beginning file, if you want you can check it out.
> 
> So we probably don’t need the Quarg ships redefined, they’ll work anyway. Also, the `outfits` means they are carrying them, not using them.

Here you said the outfits are for carrying purposes, then how do I mount them onto the fleets I desire?

**Comment by ProNooberEX** [comment]
> You have to make variants, and add them to the fleets.

Understood

**Comment by ProNooberEX** [comment]
Btw do any other contributes wish to join us?

**Comment by ProNooberEX** [comment]
> I don’t know. You can ask if you want, but not everyone will like your writing style, and may want to change it.

Is my writing style too bland?

**Comment by ProNooberEX** [comment]
Yeah true...maybe that is the case.

**Comment by ProNooberEX** [comment]
Here it says that the personalities of the pirates are "heroic", is this fitting for their character?
<img width="1227" alt="截屏2024-06-14 09 14 04" src="https://github.com/ProNooberEX/endless-sky/assets/110284440/888a78ab-628f-4191-a6b6-846fb64b4fba">

**Comment by ProNooberEX** [comment]
What does the appeasing flag do?(I can't find it in the page)

**Comment by ProNooberEX** [comment]
Should I set the Scanned fleets quarg skylance to quarg anti missle?(I think that the pirate lord would only have the ability to board two to three quarg ships, so a fleet of them would be unlikely)

**Comment by ProNooberEX** [comment]
> Shall I make the outfitter?

Go ahead

**Comment by ProNooberEX** [comment]
> > > Shall I make the outfitter?
> > 
> > 
> > Go ahead
> 
> Done.
> 
> You are aware that these ships won’t have them equipped though?
Can you make them equip these?

**Comment by ProNooberEX** [comment]
> Seeing as how it’s not private anyway-everyone can see it-and it’s not important data, it’s fine.
> 
> No problem.

Thank you so much!

**Comment by ProNooberEX** [comment]
Did you move the "Quarg Jumpers" and "Quarg Hunters" to the quarg.txt?

**Comment by ProNooberEX** [comment]
I agree, after the addition of the variants to fleets I think we are almost done with the pirate 0 txt(at least in my piratemission branch).

**Comment by ProNooberEX** [comment]
Ok

**Comment by ProNooberEX** [comment]
<img width="610" alt="截屏2024-06-14 21 33 08" src="https://github.com/ProNooberEX/endless-sky/assets/110284440/8995e8b5-810b-4747-9b30-11c80abeb93a">
I think you gave the same outfits to the Scan fleet that the Raiding Fleet uses

**Comment by ProNooberEX** [comment]
> You’re right. Do you want to try changing that or should I?

I will do it myself, no worries, do you know which file the outiftter code lay in?

**Comment by ProNooberEX** [comment]
> At the bottom of your pull request where it says checks, some of them are failing. If you want to fix those, it would be helpful.

<img width="1011" alt="截屏2024-06-14 21 51 40" src="https://github.com/ProNooberEX/endless-sky/assets/110284440/7263c741-cb18-4146-93bb-7fb4b0dd1476">
How do I view the checks themsleves?

**Comment by ProNooberEX** [comment]
Warning: fleet "Quarg Hunters" is referred to, but not fully defined.
Warning: fleet "Quarg Jumpers" is referred to, but not fully defined.
Warning: fleet "Quarg Planetary Defense" is referred to, but not fully defined.
Warning: outfit "Javalin Turret" is referred to, but not fully defined.
Warning: outfit "Modified Blaster Turrent" is referred to, but not fully defined.
Warning: phrase "Quarg" is referred to, but not fully defined.
Parse completed with at least one error(s).
Didn't we define them in the txt files?

**Comment by ProNooberEX** [comment]
<img width="994" alt="截屏2024-06-14 22 06 05" src="https://github.com/ProNooberEX/endless-sky/assets/110284440/f7aca29a-295d-40a8-9cd5-0230ca06b4ba">



> Warning: fleet "Quarg Hunters" is referred to, but not fully defined. Warning: fleet "Quarg Jumpers" is referred to, but not fully defined. Warning: fleet "Quarg Planetary Defense" is referred to, but not fully defined. Warning: outfit "Javalin Turret" is referred to, but not fully defined. Warning: outfit "Modified Blaster Turrent" is referred to, but not fully defined. Warning: phrase "Quarg" is referred to, but not fully defined. Parse completed with at least one error(s). Didn't we define them in the txt files?

**Comment by ProNooberEX** [comment]
<img width="1440" alt="截屏2024-06-16 20 39 29" src="https://github.com/ProNooberEX/endless-sky/assets/110284440/74abf2b6-63bd-40f3-bde0-3e008360253f">
I'm curious on what are the remnant new missions for, may you explain it to me?(Also I thought we are suppose ot get permission from Zitchas before adding Remnant branches?)

**Comment by ProNooberEX** [comment]
I know that in game tghere are two types of makrs, one with a bright light blue dot signalling go to there to complete missions and the other darker and says that one must jump to the systems without the need to land, how do I know which is the "mark" variable controlling?

**Comment by TheGiraffe3** [comment]
The bright one is a mission, the dark one is a waypoint. Mark is basically a new version of waypoint without the _need_ to visit it. Mark is the dark blue, I think.

**Comment by TheGiraffe3** [comment]
@ProNooberEX any objections to me putting my mission in `master`?

**Comment by TheGiraffe3** [comment]
Fixed by #10.
@ProNooberEX see my earlier comment.

**Comment by TheGiraffe3** [comment]
Closed by #10.
@ProNooberEX see my earlier comment.

**Comment by TheGiraffe3** [comment]
@ProNooberEX it looks like I've got both of our pull requests to no longer have problems!
Please review mine, #10.

**Comment by ProNooberEX** [comment]
Ok I will

**Comment by ProNooberEX** [comment]
Go ahead, I've viewed the pirate 0 mission and its ok


> Should I just squash it in now?

**Comment by ProNooberEX** [comment]
> How about we open a new conversation issue?

I think yes, because we both completed at least pirate mission 0 right?

**Comment by ProNooberEX** [comment]
> Right.

Then I suppose go ahead
